baseURL = 'https://flavorpair.me/'
languageCode = 'en-us'
title = 'The Flavor Network'
description = 'The Flavor Network is a way to build recipes based on flavor pairings.'
author = 'Wyatt Brege'
authorEmail = 'wyatt@brege.org'
authorURL = 'https://brege.org/'

theme = "PaperMod"
disableKinds = ["taxonomy"]


[permalinks]
  post = "/:year/:month/:day/:slug/"
[outputs]
  home = ["HTML"]
[taxonomies]
  category = "categories"
  tag = "tags"
  section = "sections"
  author = "authors"
[params]

  avatar = "wyatt@brege.org"

  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowReadingTime = false
  ShowWordCount = false
  ShowBreadCrumbs = false 
  ShowFullTextinRSS = true

  hideFooter = true

  [params.api]
    developmentURL = "http://localhost:5000/api/recipe"
    productionURL = "/api/recipe"
