baseURL = 'https://flavorpair.me/'
languageCode = 'en-us'
title = 'The Flavor Network'
description = 'The Flavor Network is a way to build recipes based on flavor pairings.'
author = 'Wyatt Brege'
authorEmail = 'wyatt@brege.org'
authorURL = 'https://brege.org/'

theme = "PaperMod"
disableKinds = ["taxonomy"]

[module]
  [[module.mounts]]
    source = "static/icons"
    target = "static"
  [[module.mounts]]
    source = "static"
    target = "static"


[permalinks]
  post = "/:year/:month/:day/:slug/"
[outputs]
  home = ["HTML"]
[taxonomies]
  category = "categories"
  tag = "tags"
  section = "sections"
  author = "authors"
[params]

  avatar = "wyatt@brege.org"

  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowReadingTime = false
  ShowWordCount = false
  ShowBreadCrumbs = false 
  ShowFullTextinRSS = true

  hideFooter = true
  
  [params.assets]
    favicon = "/favicon.svg"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.api]
    developmentURL = "http://localhost:5000/api/recipe"
    productionURL = "/api/recipe"
